### PR TITLE
Post types support

### PR DESCRIPTION
**Pull request by nasyrov**
Control the post types that should get the related posts metabox

Closes issue #18

### CODE REVIEW

**Comment by roborourke** [comment]
@nasyrov this looks good, I'd like to avoid any back-compat regression so can you add post type support for `post` by default? Will merge after that.

**Comment by nasyrov** [comment]
@roborourke , please have a look, updated readme guide as well.

**Comment by roborourke** [comment]
Yey, saved me a task!

**Comment by nasyrov** [comment]
@roborourke no worries, any plans to merge it and tag a new release?

**Pull request merged**
